<a href="https://colab.research.google.com/github/shalini2705/DataAnalysis/blob/main/Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
data = {
    "Name":["Ravi","Priya","Arun","Sneha","Kiran","Anjali","Vikram","Meena"],
    "Age":[22,24,21,25,23,26,20,27],
    "City":["Hyderabad","Chennai","Bangalore","Hyderabad","Mumbai","Chennai","Bengalore","Mumbai"],
    "Salary":[30000,40000,28000,50000,35000,45000,25000,55000]
}
df=pd.DataFrame(data)
print(df)
df.groupby('City')['Age'].agg(['mean','max','min'])

     Name  Age       City  Salary
0    Ravi   22  Hyderabad   30000
1   Priya   24    Chennai   40000
2    Arun   21  Bangalore   28000
3   Sneha   25  Hyderabad   50000
4   Kiran   23     Mumbai   35000
5  Anjali   26    Chennai   45000
6  Vikram   20  Bengalore   25000
7   Meena   27     Mumbai   55000

           mean  max  min
City
Bangalore  21.0   21   21
Bengalore  20.0   20   20
Chennai    25.0   26   24
Hyderabad  23.5   25   22
Mumbai     25.0   27   23

In [ ]:
df.groupby('City')['Age'].agg(['mean','max','min'])

           mean  max  min
City
Bangalore  21.0   21   21
Bengalore  20.0   20   20
Chennai    25.0   26   24
Hyderabad  23.5   25   22
Mumbai     25.0   27   23

In [ ]:
df.groupby('City').agg({'Age':['mean','max'],'Salary':['sum','count']})

            Age     Salary
           mean max    sum count
City
Bangalore  21.0  21  28000     1
Bengalore  20.0  20  25000     1
Chennai    25.0  26  85000     2
Hyderabad  23.5  25  80000     2
Mumbai     25.0  27  90000     2

In [ ]:
df1=pd.DataFrame({
    'ID':[1,2,3],
    'Name':['a','b','c']
})
df2=pd.DataFrame({
    'ID':[1,2,4],
    'Salary':[100,200,300]

})
print(df1)
print(df2)

   ID Name
0   1    a
1   2    b
2   3    c
   ID  Salary
0   1     100
1   2     200
2   4     300

In [ ]:
merged=pd.merge(
    df1,df2,on='ID',how='inner'
)
print(merged)

   ID Name  Salary
0   1    a     100
1   2    b     200

In [ ]:
merged=pd.merge(
    df1,df2,on='ID',how='left'
)
print(merged)

   ID Name  Salary
0   1    a   100.0
1   2    b   200.0
2   3    c     NaN

In [ ]:
merged=pd.merge(
    df1,df2,on='ID',how='right'
)
print(merged)

   ID Name  Salary
0   1    a     100
1   2    b     200
2   4  NaN     300

In [ ]:
merged=pd.merge(
    df1,df2,on='ID',how='outer'
)
print(merged)

   ID Name  Salary
0   1    a   100.0
1   2    b   200.0
2   3    c     NaN
3   4  NaN   300.0

In [ ]:
combined=pd.concat(
    [df1,df2],axis=0,ignore_index=True
)
print(combined)

   ID Name  Salary
0   1    a     NaN
1   2    b     NaN
2   3    c     NaN
3   1  NaN   100.0
4   2  NaN   200.0
5   4  NaN   300.0

In [ ]:
combined=pd.concat(
    [df1,df2],axis=1
)
print(combined)

   ID Name  ID  Salary
0   1    a   1     100
1   2    b   2     200
2   3    c   4     300

In [ ]:
import pandas as pd
df=pd.read_excel('/content/Sample - Superstore.csv.xlsx',)
print(df)

      Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]

In [ ]:
print(df.head())

   Row ID        Order ID Order Date  Ship Date       Ship Mode Customer ID  \
0       1  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
1       2  CA-2016-152156 2016-11-08 2016-11-11    Second Class    CG-12520
2       3  CA-2016-138688 2016-06-12 2016-06-16    Second Class    DV-13045
3       4  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335
4       5  US-2015-108966 2015-10-11 2015-10-18  Standard Class    SO-20335

     Customer Name    Segment        Country             City  ...  \
0      Claire Gute   Consumer  United States        Henderson  ...
1      Claire Gute   Consumer  United States        Henderson  ...
2  Darrin Van Huff  Corporate  United States      Los Angeles  ...
3   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...
4   Sean O'Donnell   Consumer  United States  Fort Lauderdale  ...

  Postal Code  Region       Product ID         Category Sub-Category  \
0       42420   South  FUR-BO-10001798        Furniture    Bookcases
1       42420   South  FUR-CH-10000454        Furniture       Chairs
2       90036    West  OFF-LA-10000240  Office Supplies       Labels
3       33311   South  FUR-TA-10000577        Furniture       Tables
4       33311   South  OFF-ST-10000760  Office Supplies      Storage

                                        Product Name     Sales  Quantity  \
0                  Bush Somerset Collection Bookcase  261.9600         2
1  Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2  Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3      Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                     Eldon Fold 'N Roll Cart System   22.3680         2

   Discount    Profit
0      0.00   41.9136
1      0.00  219.5820
2      0.00    6.8714
3      0.45 -383.0310
4      0.20    2.5164

[5 rows x 21 columns]

In [ ]:
print(df.tail)

<bound method NDFrame.tail of       Row ID        Order ID Order Date  Ship Date       Ship Mode  \
0          1  CA-2016-152156 2016-11-08 2016-11-11    Second Class
1          2  CA-2016-152156 2016-11-08 2016-11-11    Second Class
2          3  CA-2016-138688 2016-06-12 2016-06-16    Second Class
3          4  US-2015-108966 2015-10-11 2015-10-18  Standard Class
4          5  US-2015-108966 2015-10-11 2015-10-18  Standard Class
...      ...             ...        ...        ...             ...
9989    9990  CA-2014-110422 2014-01-21 2014-01-23    Second Class
9990    9991  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9991    9992  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9992    9993  CA-2017-121258 2017-02-26 2017-03-03  Standard Class
9993    9994  CA-2017-119914 2017-05-04 2017-05-09    Second Class

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520       Claire Gute   Consumer  United States        Henderson
1       CG-12520       Claire Gute   Consumer  United States        Henderson
2       DV-13045   Darrin Van Huff  Corporate  United States      Los Angeles
3       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
4       SO-20335    Sean O'Donnell   Consumer  United States  Fort Lauderdale
...          ...               ...        ...            ...              ...
9989    TB-21400  Tom Boeckenhauer   Consumer  United States            Miami
9990    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9991    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9992    DB-13060       Dave Brooks   Consumer  United States       Costa Mesa
9993    CC-12220      Chris Cortes   Consumer  United States      Westminster

      ... Postal Code  Region       Product ID         Category Sub-Category  \
0     ...       42420   South  FUR-BO-10001798        Furniture    Bookcases
1     ...       42420   South  FUR-CH-10000454        Furniture       Chairs
2     ...       90036    West  OFF-LA-10000240  Office Supplies       Labels
3     ...       33311   South  FUR-TA-10000577        Furniture       Tables
4     ...       33311   South  OFF-ST-10000760  Office Supplies      Storage
...   ...         ...     ...              ...              ...          ...
9989  ...       33180   South  FUR-FU-10001889        Furniture  Furnishings
9990  ...       92627    West  FUR-FU-10000747        Furniture  Furnishings
9991  ...       92627    West  TEC-PH-10003645       Technology       Phones
9992  ...       92627    West  OFF-PA-10004041  Office Supplies        Paper
9993  ...       92683    West  OFF-AP-10002684  Office Supplies   Appliances

                                           Product Name     Sales  Quantity  \
0                     Bush Somerset Collection Bookcase  261.9600         2
1     Hon Deluxe Fabric Upholstered Stacking Chairs,...  731.9400         3
2     Self-Adhesive Address Labels for Typewriters b...   14.6200         2
3         Bretford CR4500 Series Slim Rectangular Table  957.5775         5
4                        Eldon Fold 'N Roll Cart System   22.3680         2
...                                                 ...       ...       ...
9989                             Ultra Door Pull Handle   25.2480         3
9990  Tenex B1-RE Series Chair Mats for Low Pile Car...   91.9600         2
9991                              Aastra 57i VoIP phone  258.5760         2
9992  It's Hot Message Books with Stickers, 2 3/4" x 5"   29.6000         4
9993  Acco 7-Outlet Masterpiece Power Center, Wihtou...  243.1600         2

      Discount    Profit
0         0.00   41.9136
1         0.00  219.5820
2         0.00    6.8714
3         0.45 -383.0310
4         0.20    2.5164
...        ...       ...
9989      0.20    4.1028
9990      0.00   15.6332
9991      0.20   19.3932
9992      0.00   13.3200
9993      0.00   72.9480

[9994 rows x 21 columns]>

In [ ]:
print(df.len())

AttributeError: 'DataFrame' object has no attribute 'len'

In [ ]:
import pandas as pd
data={
    "EmpId":[101,102,103,104,105,106,107,108,109,110,110],
      "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
      "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
      "Salary":[30000,40000,3500,4500,32000,50000,38000,42000,36000,45000,45000]
    }
df = pd.DataFrame(data)
print(df)
df.duplicated()
df.duplicated().sum()

    EmpId    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000

np.int64(1)

In [ ]:
duplicates=df[df.duplicated(keep=False)]
print(duplicates)

    EmpId   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
d=df[df.duplicated()]
total=d["Salary"].sum()
print(total)

45000

In [ ]:
d=df[df.duplicated(keep=False)]
total=d["Salary"].sum()
print(total)

90000

In [ ]:
df['EmpId'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: EmpId, dtype: bool

In [ ]:
df['Salary'].duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
Name: Salary, dtype: bool

In [ ]:
df[df['Salary'].duplicated()]

    EmpId   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
df["City"].duplicated()
duplicates=df[df["EmpId"].duplicated()]
print(duplicates)

    EmpId   Name       City  Salary
10    110  Sneha  Hyderabad   45000

In [ ]:
duplicates=df[df["EmpId"].duplicated(keep=False)]
print(duplicates)

    EmpId   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
df[df['Name'].duplicated(keep=False)]

    EmpId   Name       City  Salary
9     110  Sneha  Hyderabad   45000
10    110  Sneha  Hyderabad   45000

In [ ]:
df=df.drop_duplicates()
print(df)

   EmpId    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI    3500
3    104   sneha    Chennai    4500
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
df=df.drop_duplicates(keep="first")
print(df)

   EmpId    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI    3500
3    104   sneha    Chennai    4500
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
df=df.drop_duplicates(keep="last")
print(df)

   EmpId    Name       City  Salary
0    101    Ravi  Hyderabad   30000
1    102   PRIYA  Hyderabad   40000
2    103    Arun    CHENNAI    3500
3    104   sneha    Chennai    4500
4    105   Kiran  Bangalore   32000
5    106  ANJALI  BANGALORE   50000
6    107  Vikram     Mumbai   38000
7    108   meena     mumbai   42000
8    109   RAHUL      Delhi   36000
9    110   Sneha  Hyderabad   45000

In [ ]:
import pandas as pd
data={
    "EmpId":[101,102,103,104,105,106,107,108,109,110,110],
      "Name":["Ravi","PRIYA","Arun","sneha","Kiran","ANJALI","Vikram","meena","RAHUL","Sneha","Sneha"],
      "City":["Hyderabad","Hyderabad","CHENNAI","Chennai","Bangalore","BANGALORE","Mumbai","mumbai","Delhi","Hyderabad","Hyderabad"],
      "Salary":[30000,40000,3500,4500,32000,50000,38000,42000,36000,45000,45000]
    }
df = pd.DataFrame(data)
print(df)
df.duplicated()
df=df.drop_duplicates(keep="last")
print(df)

    EmpId    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
9     110   Sneha  Hyderabad   45000
10    110   Sneha  Hyderabad   45000
    EmpId    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000

In [ ]:
import pandas as pd

data = {

   "TransactionID": [1001, 1002, 1003, 1004, 1005,

                      1006, 1007, 1008, 1009, 1010, 1010, 1011],

   "Customer": ["Ravi", "Priya", "Arun", "Sneha", "Kiran",

                "Anjali", "Vikram", "Meena", "Rahul", "Sneha",

                "Sneha", "Kiran"],

   "Product": ["Laptop", "Mobile", "Tablet", "Headphones", "Mouse",

               "Keyboard", "Monitor", "Laptop", "Mobile", "Headphones",

               "Headphones", "Mouse"],

   "Amount": [55000, 25000, 30000, 5000, 1500,

              2500, 18000, 55000, 22000, 5000,

              5000, 1500]}

df_sales = pd.DataFrame(data)

print(df_sales)
df.duplicated()
print(df)
df.duplicated().sum()
print(df)
duplicates=df[df.duplicated(keep=False)]
print(duplicates)

    TransactionID Customer     Product  Amount
0            1001     Ravi      Laptop   55000
1            1002    Priya      Mobile   25000
2            1003     Arun      Tablet   30000
3            1004    Sneha  Headphones    5000
4            1005    Kiran       Mouse    1500
5            1006   Anjali    Keyboard    2500
6            1007   Vikram     Monitor   18000
7            1008    Meena      Laptop   55000
8            1009    Rahul      Mobile   22000
9            1010    Sneha  Headphones    5000
10           1010    Sneha  Headphones    5000
11           1011    Kiran       Mouse    1500
    EmpId    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000
    EmpId    Name       City  Salary
0     101    Ravi  Hyderabad   30000
1     102   PRIYA  Hyderabad   40000
2     103    Arun    CHENNAI    3500
3     104   sneha    Chennai    4500
4     105   Kiran  Bangalore   32000
5     106  ANJALI  BANGALORE   50000
6     107  Vikram     Mumbai   38000
7     108   meena     mumbai   42000
8     109   RAHUL      Delhi   36000
10    110   Sneha  Hyderabad   45000
Empty DataFrame
Columns: [EmpId, Name, City, Salary]
Index: []

KeyError: np.int64(0)

   ID Name
0   1    A
1   2    B
2   3    C
3   4    D

In [ ]:
import pandas as pd
data={
    "EmpId":[101,102,103,104,105,106,107,108,109,110,110],
      "Salary":[30000,40000,3500,4500,32000,50000,38000,42000,36000,45000,45000]
    }
df = pd.DataFrame(data)
print(df)
df["Salary"]=df["Salary"].apply(lambda x: x*0.10)
print(df)

    EmpId  Salary
0     101   30000
1     102   40000
2     103    3500
3     104    4500
4     105   32000
5     106   50000
6     107   38000
7     108   42000
8     109   36000
9     110   45000
10    110   45000
    EmpId  Salary
0     101  3000.0
1     102  4000.0
2     103   350.0
3     104   450.0
4     105  3200.0
5     106  5000.0
6     107  3800.0
7     108  4200.0
8     109  3600.0
9     110  4500.0
10    110  4500.0

In [ ]:
import pandas as pd
city_code = {
   "Hyderabad": "HYD",
   "Chennai": "CHE",
   "Bangalore": "BLR",
   "Mumbai": "MUM",
   "Delhi": "DEL"
}
print(city_code)
df["city_code"] = df["city"].map(city_code)
print(city_code)

{'Hyderabad': 'HYD', 'Chennai': 'CHE', 'Bangalore': 'BLR', 'Mumbai': 'MUM', 'Delhi': 'DEL'}

KeyError: 'city'